spring.datasource.url=jdbc:postgresql://localhost:5432/mini_dish_db
spring.datasource.username=postgres
spring.datasource.password=050107
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8080
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.main.allow-bean-definition-overriding=true